import { CircleProgressOptions } from 'ng-circle-progress';

// Circle progress (on to-do list card) configuration
export const circleProgressConfig: CircleProgressOptions = {
    radius: 70,
    outerStrokeWidth: 14,
    innerStrokeWidth: 7,
    outerStrokeColor: "#78C000",
    innerStrokeColor: "#C7E596",
    animationDuration: 300,
    class: '',
    backgroundGradient: false,
    backgroundColor: '',
    backgroundGradientStopColor: '',
    backgroundOpacity: 0,
    backgroundStroke: '',
    backgroundStrokeWidth: 0,
    backgroundPadding: 0,
    percent: 0,
    space: 3,
    toFixed: 0,
    maxPercent: 100,
    renderOnClick: false,
    units: '',
    unitsFontSize: '',
    unitsFontWeight: '',
    unitsColor: '',
    outerStrokeGradient: false,
    outerStrokeGradientStopColor: '',
    outerStrokeLinecap: '',
    titleFormat: undefined,
    title: '',
    titleColor: '',
    titleFontSize: '20px',
    titleFontWeight: '',
    subtitleFormat: undefined,
    subtitle: '',
    subtitleColor: '',
    subtitleFontSize: '18px',
    subtitleFontWeight: '',
    imageSrc: undefined,
    imageHeight: 0,
    imageWidth: 0,
    animation: true,
    animateTitle: false,
    animateSubtitle: false,
    showTitle: true,
    showSubtitle: true,
    showUnits: true,
    showImage: false,
    showBackground: false,
    showInnerStroke: true,
    clockwise: true,
    responsive: false,
    startFromZero: false,
    showZeroOuterStroke: false,
    lazy: false
  };